/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Accepted
 */
export interface Accepted {
    /**
     *
     * @type {boolean}
     * @memberof Accepted
     */
    status?: boolean;
    /**
     *
     * @type {string}
     * @memberof Accepted
     */
    message?: string;
}
export declare function AcceptedFromJSON(json: any): Accepted;
export declare function AcceptedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Accepted;
export declare function AcceptedToJSON(value?: Accepted | null): any;
