/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface BulkChargeInitiate
 */
export interface BulkChargeInitiate {
    /**
     * Customer's card authorization code
     * @type {string}
     * @memberof BulkChargeInitiate
     */
    authorization: string;
    /**
     * Amount to charge on the authorization
     * @type {string}
     * @memberof BulkChargeInitiate
     */
    amount: string;
}
export declare function BulkChargeInitiateFromJSON(json: any): BulkChargeInitiate;
export declare function BulkChargeInitiateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkChargeInitiate;
export declare function BulkChargeInitiateToJSON(value?: BulkChargeInitiate | null): any;
