"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BulkChargeInitiateToJSON = exports.BulkChargeInitiateFromJSONTyped = exports.BulkChargeInitiateFromJSON = void 0;
function BulkChargeInitiateFromJSON(json) {
    return BulkChargeInitiateFromJSONTyped(json, false);
}
exports.BulkChargeInitiateFromJSON = BulkChargeInitiateFromJSON;
function BulkChargeInitiateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'authorization': json['authorization'],
        'amount': json['amount'],
    };
}
exports.BulkChargeInitiateFromJSONTyped = BulkChargeInitiateFromJSONTyped;
function BulkChargeInitiateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'authorization': value.authorization,
        'amount': value.amount,
    };
}
exports.BulkChargeInitiateToJSON = BulkChargeInitiateToJSON;
