"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChargeCreateToJSON = exports.ChargeCreateFromJSONTyped = exports.ChargeCreateFromJSON = void 0;
const runtime_1 = require("../runtime");
function ChargeCreateFromJSON(json) {
    return ChargeCreateFromJSONTyped(json, false);
}
exports.ChargeCreateFromJSON = ChargeCreateFromJSON;
function ChargeCreateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'email': json['email'],
        'amount': json['amount'],
        'authorizationCode': !runtime_1.exists(json, 'authorization_code') ? undefined : json['authorization_code'],
        'pin': !runtime_1.exists(json, 'pin') ? undefined : json['pin'],
        'reference': !runtime_1.exists(json, 'reference') ? undefined : json['reference'],
        'birthday': !runtime_1.exists(json, 'birthday') ? undefined : (new Date(json['birthday'])),
        'deviceId': !runtime_1.exists(json, 'device_id') ? undefined : json['device_id'],
        'metadata': !runtime_1.exists(json, 'metadata') ? undefined : json['metadata'],
    };
}
exports.ChargeCreateFromJSONTyped = ChargeCreateFromJSONTyped;
function ChargeCreateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'email': value.email,
        'amount': value.amount,
        'authorization_code': value.authorizationCode,
        'pin': value.pin,
        'reference': value.reference,
        'birthday': value.birthday === undefined ? undefined : (value.birthday.toISOString()),
        'device_id': value.deviceId,
        'metadata': value.metadata,
    };
}
exports.ChargeCreateToJSON = ChargeCreateToJSON;
