"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChargeSubmitPhoneToJSON = exports.ChargeSubmitPhoneFromJSONTyped = exports.ChargeSubmitPhoneFromJSON = void 0;
function ChargeSubmitPhoneFromJSON(json) {
    return ChargeSubmitPhoneFromJSONTyped(json, false);
}
exports.ChargeSubmitPhoneFromJSON = ChargeSubmitPhoneFromJSON;
function ChargeSubmitPhoneFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'phone': json['phone'],
        'reference': json['reference'],
    };
}
exports.ChargeSubmitPhoneFromJSONTyped = ChargeSubmitPhoneFromJSONTyped;
function ChargeSubmitPhoneToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'phone': value.phone,
        'reference': value.reference,
    };
}
exports.ChargeSubmitPhoneToJSON = ChargeSubmitPhoneToJSON;
