"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CustomerValidateToJSON = exports.CustomerValidateFromJSONTyped = exports.CustomerValidateFromJSON = void 0;
function CustomerValidateFromJSON(json) {
    return CustomerValidateFromJSONTyped(json, false);
}
exports.CustomerValidateFromJSON = CustomerValidateFromJSON;
function CustomerValidateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'type': json['type'],
        'value': json['value'],
        'country': json['country'],
    };
}
exports.CustomerValidateFromJSONTyped = CustomerValidateFromJSONTyped;
function CustomerValidateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'first_name': value.firstName,
        'last_name': value.lastName,
        'type': value.type,
        'value': value.value,
        'country': value.country,
    };
}
exports.CustomerValidateToJSON = CustomerValidateToJSON;
