"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CustomerDeactivateAuthorizationToJSON = exports.CustomerDeactivateAuthorizationFromJSONTyped = exports.CustomerDeactivateAuthorizationFromJSON = void 0;
function CustomerDeactivateAuthorizationFromJSON(json) {
    return CustomerDeactivateAuthorizationFromJSONTyped(json, false);
}
exports.CustomerDeactivateAuthorizationFromJSON = CustomerDeactivateAuthorizationFromJSON;
function CustomerDeactivateAuthorizationFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'authorizationCode': json['authorization_code'],
    };
}
exports.CustomerDeactivateAuthorizationFromJSONTyped = CustomerDeactivateAuthorizationFromJSONTyped;
function CustomerDeactivateAuthorizationToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'authorization_code': value.authorizationCode,
    };
}
exports.CustomerDeactivateAuthorizationToJSON = CustomerDeactivateAuthorizationToJSON;
