"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CustomerValidationToJSON = exports.CustomerValidationFromJSONTyped = exports.CustomerValidationFromJSON = void 0;
const runtime_1 = require("../runtime");
function CustomerValidationFromJSON(json) {
    return CustomerValidationFromJSONTyped(json, false);
}
exports.CustomerValidationFromJSON = CustomerValidationFromJSON;
function CustomerValidationFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'type': json['type'],
        'country': json['country'],
        'bvn': json['bvn'],
        'bankCode': json['bank_code'],
        'accountNumber': json['account_number'],
        'value': !runtime_1.exists(json, 'value') ? undefined : json['value'],
    };
}
exports.CustomerValidationFromJSONTyped = CustomerValidationFromJSONTyped;
function CustomerValidationToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'first_name': value.firstName,
        'last_name': value.lastName,
        'type': value.type,
        'country': value.country,
        'bvn': value.bvn,
        'bank_code': value.bankCode,
        'account_number': value.accountNumber,
        'value': value.value,
    };
}
exports.CustomerValidationToJSON = CustomerValidationToJSON;
