/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CustomerValidation
 */
export interface CustomerValidation {
    /**
     * Customer's first name
     * @type {string}
     * @memberof CustomerValidation
     */
    firstName: string;
    /**
     * Customer's last name
     * @type {string}
     * @memberof CustomerValidation
     */
    lastName: string;
    /**
     * Predefined types of identification.
     * @type {string}
     * @memberof CustomerValidation
     */
    type: string;
    /**
     * Two-letter country code of identification issuer
     * @type {string}
     * @memberof CustomerValidation
     */
    country: string;
    /**
     * Customer's Bank Verification Number
     * @type {string}
     * @memberof CustomerValidation
     */
    bvn: string;
    /**
     * You can get the list of bank codes by calling the List Banks endpoint (https://api.paystack.co/bank).
     * @type {string}
     * @memberof CustomerValidation
     */
    bankCode: string;
    /**
     * Customer's bank account number.
     * @type {string}
     * @memberof CustomerValidation
     */
    accountNumber: string;
    /**
     * Customer's identification number. Required if type is bvn
     * @type {string}
     * @memberof CustomerValidation
     */
    value?: string;
}
export declare function CustomerValidationFromJSON(json: any): CustomerValidation;
export declare function CustomerValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerValidation;
export declare function CustomerValidationToJSON(value?: CustomerValidation | null): any;
