/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CustomerDeactivateAuthorization
 */
export interface CustomerDeactivateAuthorization {
    /**
     * Authorization code to be deactivated
     * @type {string}
     * @memberof CustomerDeactivateAuthorization
     */
    authorizationCode: string;
}
export declare function CustomerDeactivateAuthorizationFromJSON(json: any): CustomerDeactivateAuthorization;
export declare function CustomerDeactivateAuthorizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerDeactivateAuthorization;
export declare function CustomerDeactivateAuthorizationToJSON(value?: CustomerDeactivateAuthorization | null): any;
