"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CustomerRiskActionToJSON = exports.CustomerRiskActionFromJSONTyped = exports.CustomerRiskActionFromJSON = void 0;
const runtime_1 = require("../runtime");
function CustomerRiskActionFromJSON(json) {
    return CustomerRiskActionFromJSONTyped(json, false);
}
exports.CustomerRiskActionFromJSON = CustomerRiskActionFromJSON;
function CustomerRiskActionFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'customer': json['customer'],
        'riskAction': !runtime_1.exists(json, 'risk_action') ? undefined : json['risk_action'],
    };
}
exports.CustomerRiskActionFromJSONTyped = CustomerRiskActionFromJSONTyped;
function CustomerRiskActionToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'customer': value.customer,
        'risk_action': value.riskAction,
    };
}
exports.CustomerRiskActionToJSON = CustomerRiskActionToJSON;
