/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CustomerUpdate
 */
export interface CustomerUpdate {
    /**
     * Customer's first name
     * @type {string}
     * @memberof CustomerUpdate
     */
    firstName?: string;
    /**
     * Customer's last name
     * @type {string}
     * @memberof CustomerUpdate
     */
    lastName?: string;
    /**
     * Customer's phone number
     * @type {string}
     * @memberof CustomerUpdate
     */
    phone?: string;
    /**
     * Stringified JSON object of custom data
     * @type {string}
     * @memberof CustomerUpdate
     */
    metadata?: string;
}
export declare function CustomerUpdateFromJSON(json: any): CustomerUpdate;
export declare function CustomerUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerUpdate;
export declare function CustomerUpdateToJSON(value?: CustomerUpdate | null): any;
