"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DedicatedNubanSplitToJSON = exports.DedicatedNubanSplitFromJSONTyped = exports.DedicatedNubanSplitFromJSON = void 0;
const runtime_1 = require("../runtime");
function DedicatedNubanSplitFromJSON(json) {
    return DedicatedNubanSplitFromJSONTyped(json, false);
}
exports.DedicatedNubanSplitFromJSON = DedicatedNubanSplitFromJSON;
function DedicatedNubanSplitFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'accountNumber': json['account_number'],
        'subaccount': !runtime_1.exists(json, 'subaccount') ? undefined : json['subaccount'],
        'splitCode': !runtime_1.exists(json, 'split_code') ? undefined : json['split_code'],
    };
}
exports.DedicatedNubanSplitFromJSONTyped = DedicatedNubanSplitFromJSONTyped;
function DedicatedNubanSplitToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'account_number': value.accountNumber,
        'subaccount': value.subaccount,
        'split_code': value.splitCode,
    };
}
exports.DedicatedNubanSplitToJSON = DedicatedNubanSplitToJSON;
