"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DedicatedNubanCreateToJSON = exports.DedicatedNubanCreateFromJSONTyped = exports.DedicatedNubanCreateFromJSON = void 0;
const runtime_1 = require("../runtime");
function DedicatedNubanCreateFromJSON(json) {
    return DedicatedNubanCreateFromJSONTyped(json, false);
}
exports.DedicatedNubanCreateFromJSON = DedicatedNubanCreateFromJSON;
function DedicatedNubanCreateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'customer': json['customer'],
        'preferredBank': !runtime_1.exists(json, 'preferred_bank') ? undefined : json['preferred_bank'],
        'subaccount': !runtime_1.exists(json, 'subaccount') ? undefined : json['subaccount'],
        'splitCode': !runtime_1.exists(json, 'split_code') ? undefined : json['split_code'],
    };
}
exports.DedicatedNubanCreateFromJSONTyped = DedicatedNubanCreateFromJSONTyped;
function DedicatedNubanCreateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'customer': value.customer,
        'preferred_bank': value.preferredBank,
        'subaccount': value.subaccount,
        'split_code': value.splitCode,
    };
}
exports.DedicatedNubanCreateToJSON = DedicatedNubanCreateToJSON;
