/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DedicatedNubanCreate
 */
export interface DedicatedNubanCreate {
    /**
     * Customer ID or code
     * @type {string}
     * @memberof DedicatedNubanCreate
     */
    customer: string;
    /**
     * The bank slug for preferred bank. To get a list of available banks, use the List Providers endpoint
     * @type {string}
     * @memberof DedicatedNubanCreate
     */
    preferredBank?: string;
    /**
     * Subaccount code of the account you want to split the transaction with
     * @type {string}
     * @memberof DedicatedNubanCreate
     */
    subaccount?: string;
    /**
     * Split code consisting of the lists of accounts you want to split the transaction with
     * @type {string}
     * @memberof DedicatedNubanCreate
     */
    splitCode?: string;
}
export declare function DedicatedNubanCreateFromJSON(json: any): DedicatedNubanCreate;
export declare function DedicatedNubanCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DedicatedNubanCreate;
export declare function DedicatedNubanCreateToJSON(value?: DedicatedNubanCreate | null): any;
