"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DisputeResolveToJSON = exports.DisputeResolveFromJSONTyped = exports.DisputeResolveFromJSON = void 0;
const runtime_1 = require("../runtime");
function DisputeResolveFromJSON(json) {
    return DisputeResolveFromJSONTyped(json, false);
}
exports.DisputeResolveFromJSON = DisputeResolveFromJSON;
function DisputeResolveFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'resolution': json['resolution'],
        'message': json['message'],
        'refundAmount': json['refund_amount'],
        'uploadedFilename': json['uploaded_filename'],
        'evidence': !runtime_1.exists(json, 'evidence') ? undefined : json['evidence'],
    };
}
exports.DisputeResolveFromJSONTyped = DisputeResolveFromJSONTyped;
function DisputeResolveToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'resolution': value.resolution,
        'message': value.message,
        'refund_amount': value.refundAmount,
        'uploaded_filename': value.uploadedFilename,
        'evidence': value.evidence,
    };
}
exports.DisputeResolveToJSON = DisputeResolveToJSON;
