"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EFTToJSON = exports.EFTFromJSONTyped = exports.EFTFromJSON = void 0;
const runtime_1 = require("../runtime");
function EFTFromJSON(json) {
    return EFTFromJSONTyped(json, false);
}
exports.EFTFromJSON = EFTFromJSON;
function EFTFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'provider': !runtime_1.exists(json, 'provider') ? undefined : json['provider'],
    };
}
exports.EFTFromJSONTyped = EFTFromJSONTyped;
function EFTToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'provider': value.provider,
    };
}
exports.EFTToJSON = EFTToJSON;
