"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MobileMoneyToJSON = exports.MobileMoneyFromJSONTyped = exports.MobileMoneyFromJSON = void 0;
const runtime_1 = require("../runtime");
function MobileMoneyFromJSON(json) {
    return MobileMoneyFromJSONTyped(json, false);
}
exports.MobileMoneyFromJSON = MobileMoneyFromJSON;
function MobileMoneyFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'phone': !runtime_1.exists(json, 'phone') ? undefined : json['phone'],
        'provider': !runtime_1.exists(json, 'provider') ? undefined : json['provider'],
    };
}
exports.MobileMoneyFromJSONTyped = MobileMoneyFromJSONTyped;
function MobileMoneyToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'phone': value.phone,
        'provider': value.provider,
    };
}
exports.MobileMoneyToJSON = MobileMoneyToJSON;
