"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PageCreateToJSON = exports.PageCreateFromJSONTyped = exports.PageCreateFromJSON = void 0;
const runtime_1 = require("../runtime");
function PageCreateFromJSON(json) {
    return PageCreateFromJSONTyped(json, false);
}
exports.PageCreateFromJSON = PageCreateFromJSON;
function PageCreateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'name': json['name'],
        'description': !runtime_1.exists(json, 'description') ? undefined : json['description'],
        'amount': !runtime_1.exists(json, 'amount') ? undefined : json['amount'],
        'slug': !runtime_1.exists(json, 'slug') ? undefined : json['slug'],
        'metadata': !runtime_1.exists(json, 'metadata') ? undefined : json['metadata'],
        'redirectUrl': !runtime_1.exists(json, 'redirect_url') ? undefined : json['redirect_url'],
        'customFields': !runtime_1.exists(json, 'custom_fields') ? undefined : json['custom_fields'],
    };
}
exports.PageCreateFromJSONTyped = PageCreateFromJSONTyped;
function PageCreateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'name': value.name,
        'description': value.description,
        'amount': value.amount,
        'slug': value.slug,
        'metadata': value.metadata,
        'redirect_url': value.redirectUrl,
        'custom_fields': value.customFields,
    };
}
exports.PageCreateToJSON = PageCreateToJSON;
