"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PageUpdateToJSON = exports.PageUpdateFromJSONTyped = exports.PageUpdateFromJSON = void 0;
const runtime_1 = require("../runtime");
function PageUpdateFromJSON(json) {
    return PageUpdateFromJSONTyped(json, false);
}
exports.PageUpdateFromJSON = PageUpdateFromJSON;
function PageUpdateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'name': !runtime_1.exists(json, 'name') ? undefined : json['name'],
        'description': !runtime_1.exists(json, 'description') ? undefined : json['description'],
        'amount': !runtime_1.exists(json, 'amount') ? undefined : json['amount'],
        'active': !runtime_1.exists(json, 'active') ? undefined : json['active'],
    };
}
exports.PageUpdateFromJSONTyped = PageUpdateFromJSONTyped;
function PageUpdateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'name': value.name,
        'description': value.description,
        'amount': value.amount,
        'active': value.active,
    };
}
exports.PageUpdateToJSON = PageUpdateToJSON;
