/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PlanCreate
 */
export interface PlanCreate {
    /**
     * Name of plan
     * @type {string}
     * @memberof PlanCreate
     */
    name: string;
    /**
     * Amount should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR
     * @type {number}
     * @memberof PlanCreate
     */
    amount: number;
    /**
     * Interval in words. Valid intervals are daily, weekly, monthly,biannually, annually
     * @type {string}
     * @memberof PlanCreate
     */
    interval: string;
    /**
     * A description for this plan
     * @type {boolean}
     * @memberof PlanCreate
     */
    description?: boolean;
    /**
     * Set to false if you don't want invoices to be sent to your customers
     * @type {boolean}
     * @memberof PlanCreate
     */
    sendInvoices?: boolean;
    /**
     * Set to false if you don't want text messages to be sent to your customers
     * @type {boolean}
     * @memberof PlanCreate
     */
    sendSms?: boolean;
    /**
     * Currency in which amount is set. Allowed values are NGN, GHS, ZAR or USD
     * @type {string}
     * @memberof PlanCreate
     */
    currency?: string;
    /**
     * Number of invoices to raise during subscription to this plan.
     * Can be overridden by specifying an invoice_limit while subscribing.
     * @type {number}
     * @memberof PlanCreate
     */
    invoiceLimit?: number;
}
export declare function PlanCreateFromJSON(json: any): PlanCreate;
export declare function PlanCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanCreate;
export declare function PlanCreateToJSON(value?: PlanCreate | null): any;
