"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PlanUpdateToJSON = exports.PlanUpdateFromJSONTyped = exports.PlanUpdateFromJSON = void 0;
const runtime_1 = require("../runtime");
function PlanUpdateFromJSON(json) {
    return PlanUpdateFromJSONTyped(json, false);
}
exports.PlanUpdateFromJSON = PlanUpdateFromJSON;
function PlanUpdateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'name': !runtime_1.exists(json, 'name') ? undefined : json['name'],
        'amount': !runtime_1.exists(json, 'amount') ? undefined : json['amount'],
        'interval': !runtime_1.exists(json, 'interval') ? undefined : json['interval'],
        'description': !runtime_1.exists(json, 'description') ? undefined : json['description'],
        'sendInvoices': !runtime_1.exists(json, 'send_invoices') ? undefined : json['send_invoices'],
        'sendSms': !runtime_1.exists(json, 'send_sms') ? undefined : json['send_sms'],
        'currency': !runtime_1.exists(json, 'currency') ? undefined : json['currency'],
        'invoiceLimit': !runtime_1.exists(json, 'invoice_limit') ? undefined : json['invoice_limit'],
    };
}
exports.PlanUpdateFromJSONTyped = PlanUpdateFromJSONTyped;
function PlanUpdateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'name': value.name,
        'amount': value.amount,
        'interval': value.interval,
        'description': value.description,
        'send_invoices': value.sendInvoices,
        'send_sms': value.sendSms,
        'currency': value.currency,
        'invoice_limit': value.invoiceLimit,
    };
}
exports.PlanUpdateToJSON = PlanUpdateToJSON;
