/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface RefundCreate
 */
export interface RefundCreate {
    /**
     * Transaction reference or id
     * @type {string}
     * @memberof RefundCreate
     */
    transaction: string;
    /**
     * Amount ( in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR ) to be refunded to the customer.
     * Amount cannot be more than the original transaction amount
     * @type {number}
     * @memberof RefundCreate
     */
    amount?: number;
    /**
     * Three-letter ISO currency. Allowed values are NGN, GHS, ZAR or USD
     * @type {string}
     * @memberof RefundCreate
     */
    currency?: string;
    /**
     * Customer reason
     * @type {string}
     * @memberof RefundCreate
     */
    customerNote?: string;
    /**
     * Merchant reason
     * @type {string}
     * @memberof RefundCreate
     */
    merchantNote?: string;
}
export declare function RefundCreateFromJSON(json: any): RefundCreate;
export declare function RefundCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundCreate;
export declare function RefundCreateToJSON(value?: RefundCreate | null): any;
