"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RefundCreateToJSON = exports.RefundCreateFromJSONTyped = exports.RefundCreateFromJSON = void 0;
const runtime_1 = require("../runtime");
function RefundCreateFromJSON(json) {
    return RefundCreateFromJSONTyped(json, false);
}
exports.RefundCreateFromJSON = RefundCreateFromJSON;
function RefundCreateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'transaction': json['transaction'],
        'amount': !runtime_1.exists(json, 'amount') ? undefined : json['amount'],
        'currency': !runtime_1.exists(json, 'currency') ? undefined : json['currency'],
        'customerNote': !runtime_1.exists(json, 'customer_note') ? undefined : json['customer_note'],
        'merchantNote': !runtime_1.exists(json, 'merchant_note') ? undefined : json['merchant_note'],
    };
}
exports.RefundCreateFromJSONTyped = RefundCreateFromJSONTyped;
function RefundCreateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'transaction': value.transaction,
        'amount': value.amount,
        'currency': value.currency,
        'customer_note': value.customerNote,
        'merchant_note': value.merchantNote,
    };
}
exports.RefundCreateToJSON = RefundCreateToJSON;
