"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResponseToJSON = exports.ResponseFromJSONTyped = exports.ResponseFromJSON = void 0;
const runtime_1 = require("../runtime");
function ResponseFromJSON(json) {
    return ResponseFromJSONTyped(json, false);
}
exports.ResponseFromJSON = ResponseFromJSON;
function ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'status': !runtime_1.exists(json, 'status') ? undefined : json['status'],
        'message': !runtime_1.exists(json, 'message') ? undefined : json['message'],
        'data': !runtime_1.exists(json, 'data') ? undefined : json['data'],
    };
}
exports.ResponseFromJSONTyped = ResponseFromJSONTyped;
function ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'status': value.status,
        'message': value.message,
        'data': value.data,
    };
}
exports.ResponseToJSON = ResponseToJSON;
