"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SplitCreateToJSON = exports.SplitCreateFromJSONTyped = exports.SplitCreateFromJSON = void 0;
const runtime_1 = require("../runtime");
const _1 = require("./");
function SplitCreateFromJSON(json) {
    return SplitCreateFromJSONTyped(json, false);
}
exports.SplitCreateFromJSON = SplitCreateFromJSON;
function SplitCreateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'name': json['name'],
        'type': json['type'],
        'subaccounts': (json['subaccounts'].map(_1.SplitSubaccountsFromJSON)),
        'currency': json['currency'],
        'bearerType': !runtime_1.exists(json, 'bearer_type') ? undefined : json['bearer_type'],
        'bearerSubaccount': !runtime_1.exists(json, 'bearer_subaccount') ? undefined : json['bearer_subaccount'],
    };
}
exports.SplitCreateFromJSONTyped = SplitCreateFromJSONTyped;
function SplitCreateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'name': value.name,
        'type': value.type,
        'subaccounts': (value.subaccounts.map(_1.SplitSubaccountsToJSON)),
        'currency': value.currency,
        'bearer_type': value.bearerType,
        'bearer_subaccount': value.bearerSubaccount,
    };
}
exports.SplitCreateToJSON = SplitCreateToJSON;
