"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SplitSubaccountsToJSON = exports.SplitSubaccountsFromJSONTyped = exports.SplitSubaccountsFromJSON = void 0;
const runtime_1 = require("../runtime");
function SplitSubaccountsFromJSON(json) {
    return SplitSubaccountsFromJSONTyped(json, false);
}
exports.SplitSubaccountsFromJSON = SplitSubaccountsFromJSON;
function SplitSubaccountsFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'subaccount': !runtime_1.exists(json, 'subaccount') ? undefined : json['subaccount'],
        'share': !runtime_1.exists(json, 'share') ? undefined : json['share'],
    };
}
exports.SplitSubaccountsFromJSONTyped = SplitSubaccountsFromJSONTyped;
function SplitSubaccountsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'subaccount': value.subaccount,
        'share': value.share,
    };
}
exports.SplitSubaccountsToJSON = SplitSubaccountsToJSON;
