"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubaccountUpdateToJSON = exports.SubaccountUpdateFromJSONTyped = exports.SubaccountUpdateFromJSON = void 0;
const runtime_1 = require("../runtime");
function SubaccountUpdateFromJSON(json) {
    return SubaccountUpdateFromJSONTyped(json, false);
}
exports.SubaccountUpdateFromJSON = SubaccountUpdateFromJSON;
function SubaccountUpdateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'businessName': !runtime_1.exists(json, 'business_name') ? undefined : json['business_name'],
        'settlementBank': !runtime_1.exists(json, 'settlement_bank') ? undefined : json['settlement_bank'],
        'accountNumber': !runtime_1.exists(json, 'account_number') ? undefined : json['account_number'],
        'active': !runtime_1.exists(json, 'active') ? undefined : json['active'],
        'percentageCharge': !runtime_1.exists(json, 'percentage_charge') ? undefined : json['percentage_charge'],
        'description': !runtime_1.exists(json, 'description') ? undefined : json['description'],
        'primaryContactEmail': !runtime_1.exists(json, 'primary_contact_email') ? undefined : json['primary_contact_email'],
        'primaryContactName': !runtime_1.exists(json, 'primary_contact_name') ? undefined : json['primary_contact_name'],
        'primaryContactPhone': !runtime_1.exists(json, 'primary_contact_phone') ? undefined : json['primary_contact_phone'],
        'metadata': !runtime_1.exists(json, 'metadata') ? undefined : json['metadata'],
    };
}
exports.SubaccountUpdateFromJSONTyped = SubaccountUpdateFromJSONTyped;
function SubaccountUpdateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'business_name': value.businessName,
        'settlement_bank': value.settlementBank,
        'account_number': value.accountNumber,
        'active': value.active,
        'percentage_charge': value.percentageCharge,
        'description': value.description,
        'primary_contact_email': value.primaryContactEmail,
        'primary_contact_name': value.primaryContactName,
        'primary_contact_phone': value.primaryContactPhone,
        'metadata': value.metadata,
    };
}
exports.SubaccountUpdateToJSON = SubaccountUpdateToJSON;
