"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubscriptionCreateToJSON = exports.SubscriptionCreateFromJSONTyped = exports.SubscriptionCreateFromJSON = void 0;
const runtime_1 = require("../runtime");
function SubscriptionCreateFromJSON(json) {
    return SubscriptionCreateFromJSONTyped(json, false);
}
exports.SubscriptionCreateFromJSON = SubscriptionCreateFromJSON;
function SubscriptionCreateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'customer': json['customer'],
        'plan': json['plan'],
        'authorization': !runtime_1.exists(json, 'authorization') ? undefined : json['authorization'],
        'startDate': !runtime_1.exists(json, 'start_date') ? undefined : (new Date(json['start_date'])),
    };
}
exports.SubscriptionCreateFromJSONTyped = SubscriptionCreateFromJSONTyped;
function SubscriptionCreateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'customer': value.customer,
        'plan': value.plan,
        'authorization': value.authorization,
        'start_date': value.startDate === undefined ? undefined : (value.startDate.toISOString()),
    };
}
exports.SubscriptionCreateToJSON = SubscriptionCreateToJSON;
