/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SubscriptionToggle
 */
export interface SubscriptionToggle {
    /**
     * Subscription code
     * @type {string}
     * @memberof SubscriptionToggle
     */
    code: string;
    /**
     * Email token
     * @type {string}
     * @memberof SubscriptionToggle
     */
    token: string;
}
export declare function SubscriptionToggleFromJSON(json: any): SubscriptionToggle;
export declare function SubscriptionToggleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionToggle;
export declare function SubscriptionToggleToJSON(value?: SubscriptionToggle | null): any;
