"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferRecipientCreateToJSON = exports.TransferRecipientCreateFromJSONTyped = exports.TransferRecipientCreateFromJSON = void 0;
const runtime_1 = require("../runtime");
function TransferRecipientCreateFromJSON(json) {
    return TransferRecipientCreateFromJSONTyped(json, false);
}
exports.TransferRecipientCreateFromJSON = TransferRecipientCreateFromJSON;
function TransferRecipientCreateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'type': json['type'],
        'name': json['name'],
        'accountNumber': json['account_number'],
        'bankCode': json['bank_code'],
        'description': !runtime_1.exists(json, 'description') ? undefined : json['description'],
        'currency': !runtime_1.exists(json, 'currency') ? undefined : json['currency'],
        'authorizationCode': !runtime_1.exists(json, 'authorization_code') ? undefined : json['authorization_code'],
        'metadata': !runtime_1.exists(json, 'metadata') ? undefined : json['metadata'],
    };
}
exports.TransferRecipientCreateFromJSONTyped = TransferRecipientCreateFromJSONTyped;
function TransferRecipientCreateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'type': value.type,
        'name': value.name,
        'account_number': value.accountNumber,
        'bank_code': value.bankCode,
        'description': value.description,
        'currency': value.currency,
        'authorization_code': value.authorizationCode,
        'metadata': value.metadata,
    };
}
exports.TransferRecipientCreateToJSON = TransferRecipientCreateToJSON;
