/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransferInitiate } from './';
/**
 *
 * @export
 * @interface TransferBulk
 */
export interface TransferBulk {
    /**
     * Where should we transfer from? Only balance is allowed for now
     * @type {string}
     * @memberof TransferBulk
     */
    source?: string;
    /**
     * A list of transfer object. Each object should contain amount, recipient, and reference
     * @type {Array<TransferInitiate>}
     * @memberof TransferBulk
     */
    transfers?: Array<TransferInitiate>;
}
export declare function TransferBulkFromJSON(json: any): TransferBulk;
export declare function TransferBulkFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferBulk;
export declare function TransferBulkToJSON(value?: TransferBulk | null): any;
