"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferInitiateToJSON = exports.TransferInitiateFromJSONTyped = exports.TransferInitiateFromJSON = void 0;
const runtime_1 = require("../runtime");
function TransferInitiateFromJSON(json) {
    return TransferInitiateFromJSONTyped(json, false);
}
exports.TransferInitiateFromJSON = TransferInitiateFromJSON;
function TransferInitiateFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'source': json['source'],
        'amount': json['amount'],
        'recipient': json['recipient'],
        'reason': !runtime_1.exists(json, 'reason') ? undefined : json['reason'],
        'currency': !runtime_1.exists(json, 'currency') ? undefined : json['currency'],
        'reference': !runtime_1.exists(json, 'reference') ? undefined : json['reference'],
    };
}
exports.TransferInitiateFromJSONTyped = TransferInitiateFromJSONTyped;
function TransferInitiateToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'source': value.source,
        'amount': value.amount,
        'recipient': value.recipient,
        'reason': value.reason,
        'currency': value.currency,
        'reference': value.reference,
    };
}
exports.TransferInitiateToJSON = TransferInitiateToJSON;
