"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferResendOTPToJSON = exports.TransferResendOTPFromJSONTyped = exports.TransferResendOTPFromJSON = void 0;
function TransferResendOTPFromJSON(json) {
    return TransferResendOTPFromJSONTyped(json, false);
}
exports.TransferResendOTPFromJSON = TransferResendOTPFromJSON;
function TransferResendOTPFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'transferCode': json['transfer_code'],
        'reason': json['reason'],
    };
}
exports.TransferResendOTPFromJSONTyped = TransferResendOTPFromJSONTyped;
function TransferResendOTPToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'transfer_code': value.transferCode,
        'reason': value.reason,
    };
}
exports.TransferResendOTPToJSON = TransferResendOTPToJSON;
