"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferRecipientBulkToJSON = exports.TransferRecipientBulkFromJSONTyped = exports.TransferRecipientBulkFromJSON = void 0;
const _1 = require("./");
function TransferRecipientBulkFromJSON(json) {
    return TransferRecipientBulkFromJSONTyped(json, false);
}
exports.TransferRecipientBulkFromJSON = TransferRecipientBulkFromJSON;
function TransferRecipientBulkFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'batch': (json['batch'].map(_1.TransferRecipientCreateFromJSON)),
    };
}
exports.TransferRecipientBulkFromJSONTyped = TransferRecipientBulkFromJSONTyped;
function TransferRecipientBulkToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'batch': (value.batch.map(_1.TransferRecipientCreateToJSON)),
    };
}
exports.TransferRecipientBulkToJSON = TransferRecipientBulkToJSON;
