"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionPartialDebitToJSON = exports.TransactionPartialDebitFromJSONTyped = exports.TransactionPartialDebitFromJSON = void 0;
const runtime_1 = require("../runtime");
function TransactionPartialDebitFromJSON(json) {
    return TransactionPartialDebitFromJSONTyped(json, false);
}
exports.TransactionPartialDebitFromJSON = TransactionPartialDebitFromJSON;
function TransactionPartialDebitFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'email': json['email'],
        'amount': json['amount'],
        'authorizationCode': json['authorization_code'],
        'currency': json['currency'],
        'reference': !runtime_1.exists(json, 'reference') ? undefined : json['reference'],
        'atLeast': !runtime_1.exists(json, 'at_least') ? undefined : json['at_least'],
    };
}
exports.TransactionPartialDebitFromJSONTyped = TransactionPartialDebitFromJSONTyped;
function TransactionPartialDebitToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'email': value.email,
        'amount': value.amount,
        'authorization_code': value.authorizationCode,
        'currency': value.currency,
        'reference': value.reference,
        'at_least': value.atLeast,
    };
}
exports.TransactionPartialDebitToJSON = TransactionPartialDebitToJSON;
