"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionChargeAuthorizationToJSON = exports.TransactionChargeAuthorizationFromJSONTyped = exports.TransactionChargeAuthorizationFromJSON = void 0;
const runtime_1 = require("../runtime");
function TransactionChargeAuthorizationFromJSON(json) {
    return TransactionChargeAuthorizationFromJSONTyped(json, false);
}
exports.TransactionChargeAuthorizationFromJSON = TransactionChargeAuthorizationFromJSON;
function TransactionChargeAuthorizationFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'email': json['email'],
        'amount': json['amount'],
        'authorizationCode': json['authorization_code'],
        'reference': !runtime_1.exists(json, 'reference') ? undefined : json['reference'],
        'currency': !runtime_1.exists(json, 'currency') ? undefined : json['currency'],
        'metadata': !runtime_1.exists(json, 'metadata') ? undefined : json['metadata'],
        'splitCode': !runtime_1.exists(json, 'split_code') ? undefined : json['split_code'],
        'subaccount': !runtime_1.exists(json, 'subaccount') ? undefined : json['subaccount'],
        'transactionCharge': !runtime_1.exists(json, 'transaction_charge') ? undefined : json['transaction_charge'],
        'bearer': !runtime_1.exists(json, 'bearer') ? undefined : json['bearer'],
        'queue': !runtime_1.exists(json, 'queue') ? undefined : json['queue'],
    };
}
exports.TransactionChargeAuthorizationFromJSONTyped = TransactionChargeAuthorizationFromJSONTyped;
function TransactionChargeAuthorizationToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'email': value.email,
        'amount': value.amount,
        'authorization_code': value.authorizationCode,
        'reference': value.reference,
        'currency': value.currency,
        'metadata': value.metadata,
        'split_code': value.splitCode,
        'subaccount': value.subaccount,
        'transaction_charge': value.transactionCharge,
        'bearer': value.bearer,
        'queue': value.queue,
    };
}
exports.TransactionChargeAuthorizationToJSON = TransactionChargeAuthorizationToJSON;
