"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionCheckAuthorizationToJSON = exports.TransactionCheckAuthorizationFromJSONTyped = exports.TransactionCheckAuthorizationFromJSON = void 0;
const runtime_1 = require("../runtime");
function TransactionCheckAuthorizationFromJSON(json) {
    return TransactionCheckAuthorizationFromJSONTyped(json, false);
}
exports.TransactionCheckAuthorizationFromJSON = TransactionCheckAuthorizationFromJSON;
function TransactionCheckAuthorizationFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'email': json['email'],
        'amount': json['amount'],
        'authorizationCode': !runtime_1.exists(json, 'authorization_code') ? undefined : json['authorization_code'],
        'currency': !runtime_1.exists(json, 'currency') ? undefined : json['currency'],
    };
}
exports.TransactionCheckAuthorizationFromJSONTyped = TransactionCheckAuthorizationFromJSONTyped;
function TransactionCheckAuthorizationToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'email': value.email,
        'amount': value.amount,
        'authorization_code': value.authorizationCode,
        'currency': value.currency,
    };
}
exports.TransactionCheckAuthorizationToJSON = TransactionCheckAuthorizationToJSON;
