/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface VerificationBVNMatch
 */
export interface VerificationBVNMatch {
    /**
     * Bank Account Number
     * @type {string}
     * @memberof VerificationBVNMatch
     */
    accountNumber: string;
    /**
     * You can get the list of banks codes by calling the List Bank endpoint
     * @type {number}
     * @memberof VerificationBVNMatch
     */
    bankCode: number;
    /**
     * 11 digits Bank Verification Number
     * @type {string}
     * @memberof VerificationBVNMatch
     */
    bvn: string;
    /**
     * Customer's first name
     * @type {string}
     * @memberof VerificationBVNMatch
     */
    firstName?: string;
    /**
     * Customer's middle name
     * @type {string}
     * @memberof VerificationBVNMatch
     */
    middleName?: string;
    /**
     * Customer's last name
     * @type {string}
     * @memberof VerificationBVNMatch
     */
    lastName?: string;
}
export declare function VerificationBVNMatchFromJSON(json: any): VerificationBVNMatch;
export declare function VerificationBVNMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationBVNMatch;
export declare function VerificationBVNMatchToJSON(value?: VerificationBVNMatch | null): any;
