/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseAPI } from '../runtime';
import { Response } from '../models';
export interface ChargesRequest {
    code: string;
}
export interface FetchRequest {
    code: string;
}
export interface ListRequest {
    perPage?: number;
    page?: number;
    from?: Date;
    to?: Date;
}
export interface PauseRequest {
    code: string;
}
export interface ResumeRequest {
    code: string;
}
/**
 *
 */
export declare class BulkCharge extends BaseAPI {
    /**
     * Fetch Charges in a Batch
     */
    charges(requestParameters: ChargesRequest): Promise<Response>;
    /**
     * Fetch Bulk Charge Batch
     */
    fetch(requestParameters: FetchRequest): Promise<Response>;
    /**
     * Initiate Bulk Charge
     */
    initiate(): Promise<Response>;
    /**
     * List Bulk Charge Batches
     */
    list(requestParameters: ListRequest): Promise<Response>;
    /**
     * Pause Bulk Charge Batch
     */
    pause(requestParameters: PauseRequest): Promise<Response>;
    /**
     * Resume Bulk Charge Batch
     */
    resume(requestParameters: ResumeRequest): Promise<Response>;
}
