/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseAPI } from '../runtime';
import { Response } from '../models';
export interface CreateRequest {
    name: string;
    amount: number;
    interval: string;
    description?: boolean;
    send_invoices?: boolean;
    send_sms?: boolean;
    currency?: string;
    invoice_limit?: number;
}
export interface FetchRequest {
    code: string;
}
export interface ListRequest {
    perPage?: number;
    page?: number;
    interval?: string;
    amount?: number;
    from?: Date;
    to?: Date;
}
export interface UpdateRequest {
    code: string;
    name?: string;
    amount?: number;
    interval?: string;
    description?: boolean;
    send_invoices?: boolean;
    send_sms?: boolean;
    currency?: string;
    invoice_limit?: number;
}
/**
 *
 */
export declare class Plan extends BaseAPI {
    /**
     * Create Plan
     */
    create(requestParameters: CreateRequest): Promise<Response>;
    /**
     * Fetch Plan
     */
    fetch(requestParameters: FetchRequest): Promise<Response>;
    /**
     * List Plans
     */
    list(requestParameters: ListRequest): Promise<Response>;
    /**
     * Update Plan
     */
    update(requestParameters: UpdateRequest): Promise<Response>;
}
