/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseAPI } from '../runtime';
import { Response, SplitSubaccounts } from '../models';
export interface AddSubaccountRequest {
    id: string;
    subaccount?: string;
    share?: string;
}
export interface CreateRequest {
    name: string;
    type: string;
    subaccounts: Array<SplitSubaccounts>;
    currency: string;
    bearer_type?: string;
    bearer_subaccount?: string;
}
export interface FetchRequest {
    id: string;
}
export interface ListRequest {
    name?: string;
    active?: string;
    sort_by?: string;
    from?: string;
    to?: string;
    perPage?: string;
    page?: string;
}
export interface RemoveSubaccountRequest {
    id: string;
    subaccount?: string;
    share?: string;
}
export interface UpdateRequest {
    id: string;
    name?: string;
    active?: boolean;
    bearer_type?: string;
    bearer_subaccount?: string;
}
/**
 *
 */
export declare class Split extends BaseAPI {
    /**
     * Add Subaccount to Split
     */
    addSubaccount(requestParameters: AddSubaccountRequest): Promise<Response>;
    /**
     * Create Split
     */
    create(requestParameters: CreateRequest): Promise<Response>;
    /**
     * Fetch Split
     */
    fetch(requestParameters: FetchRequest): Promise<Response>;
    /**
     * List/Search Splits
     */
    list(requestParameters: ListRequest): Promise<Response>;
    /**
     * Remove Subaccount from split
     */
    removeSubaccount(requestParameters: RemoveSubaccountRequest): Promise<Response>;
    /**
     * Update Split
     */
    update(requestParameters: UpdateRequest): Promise<Response>;
}
