/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseAPI } from '../runtime';
import { Response, TransferRecipientCreate } from '../models';
export interface BulkRequest {
    batch: Array<TransferRecipientCreate>;
}
export interface CreateRequest {
    type: string;
    name: string;
    account_number: string;
    bank_code: string;
    description?: string;
    currency?: string;
    authorization_code?: string;
    metadata?: string;
}
export interface FetchRequest {
    code: string;
}
export interface ListRequest {
    perPage?: number;
    page?: number;
    from?: Date;
    to?: Date;
}
export interface TransferrecipientCodeDeleteRequest {
    code: string;
}
export interface TransferrecipientCodePutRequest {
    code: string;
    name?: string;
    email?: string;
}
/**
 *
 */
export declare class TransferRecipient extends BaseAPI {
    /**
     * Bulk Create Transfer Recipient
     */
    bulk(requestParameters: BulkRequest): Promise<Response>;
    /**
     * Create Transfer Recipient
     */
    create(requestParameters: CreateRequest): Promise<Response>;
    /**
     * Fetch Transfer recipient
     */
    fetch(requestParameters: FetchRequest): Promise<Response>;
    /**
     * List Transfer Recipients
     */
    list(requestParameters: ListRequest): Promise<Response>;
    /**
     * Delete Transfer Recipient
     */
    transferrecipientCodeDelete(requestParameters: TransferrecipientCodeDeleteRequest): Promise<Response>;
    /**
     * Update Transfer recipient
     */
    transferrecipientCodePut(requestParameters: TransferrecipientCodePutRequest): Promise<Response>;
}
