/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChargeSubmitPhone
 */
export interface ChargeSubmitPhone {
    /**
     * Customer's mobile number
     * @type {string}
     * @memberof ChargeSubmitPhone
     */
    phone: string;
    /**
     * The reference of the ongoing transaction
     * @type {string}
     * @memberof ChargeSubmitPhone
     */
    reference: string;
}

export function ChargeSubmitPhoneFromJSON(json: any): ChargeSubmitPhone {
    return ChargeSubmitPhoneFromJSONTyped(json, false);
}

export function ChargeSubmitPhoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChargeSubmitPhone {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'phone': json['phone'],
        'reference': json['reference'],
    };
}

export function ChargeSubmitPhoneToJSON(value?: ChargeSubmitPhone | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'phone': value.phone,
        'reference': value.reference,
    };
}


