/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChargeSubmitBirthday
 */
export interface ChargeSubmitBirthday {
    /**
     * Customer's birthday in the format YYYY-MM-DD e.g 2016-09-21
     * @type {string}
     * @memberof ChargeSubmitBirthday
     */
    birthday: string;
    /**
     * The reference of the ongoing transaction
     * @type {string}
     * @memberof ChargeSubmitBirthday
     */
    reference: string;
}

export function ChargeSubmitBirthdayFromJSON(json: any): ChargeSubmitBirthday {
    return ChargeSubmitBirthdayFromJSONTyped(json, false);
}

export function ChargeSubmitBirthdayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChargeSubmitBirthday {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'birthday': json['birthday'],
        'reference': json['reference'],
    };
}

export function ChargeSubmitBirthdayToJSON(value?: ChargeSubmitBirthday | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'birthday': value.birthday,
        'reference': value.reference,
    };
}


