export interface CustomerFetchData {
  /**  */
  transactions: Array<unknown>;
  /**  */
  subscriptions: Array<unknown>;
  /**  */
  authorizations: Array<unknown>;
  /**  */
  first_name: string;
  /**  */
  last_name: string;
  /**  */
  email: string;
  /**  */
  phone: string;
  /**  */
  metadata: { calling_code?: string };
  /**  */
  domain: string;
  /**  */
  customer_code: string;
  /**  */
  risk_action: string;
  /**  */
  id: number;
  /**  */
  integration: number;
  /**  */
  createdAt: string;
  /**  */
  updatedAt: string;
  /**  */
  created_at: string;
  /**  */
  updated_at: string;
  /**  */
  total_transactions: number;
  /**  */
  total_transaction_value: Array<unknown>;
  /**  */
  dedicated_account: unknown;
  /**  */
  dedicated_accounts: Array<unknown>;
  /**  */
  identified: boolean;
  /**  */
  identifications: unknown;
}
