/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerValidation
 */
export interface CustomerValidation {
    /**
     * Customer's first name
     * @type {string}
     * @memberof CustomerValidation
     */
    firstName: string;
    /**
     * Customer's last name
     * @type {string}
     * @memberof CustomerValidation
     */
    lastName: string;
    /**
     * Predefined types of identification.
     * @type {string}
     * @memberof CustomerValidation
     */
    type: string;
    /**
     * Two-letter country code of identification issuer
     * @type {string}
     * @memberof CustomerValidation
     */
    country: string;
    /**
     * Customer's Bank Verification Number
     * @type {string}
     * @memberof CustomerValidation
     */
    bvn: string;
    /**
     * You can get the list of bank codes by calling the List Banks endpoint (https://api.paystack.co/bank).
     * @type {string}
     * @memberof CustomerValidation
     */
    bankCode: string;
    /**
     * Customer's bank account number.
     * @type {string}
     * @memberof CustomerValidation
     */
    accountNumber: string;
    /**
     * Customer's identification number. Required if type is bvn
     * @type {string}
     * @memberof CustomerValidation
     */
    value?: string;
}

export function CustomerValidationFromJSON(json: any): CustomerValidation {
    return CustomerValidationFromJSONTyped(json, false);
}

export function CustomerValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerValidation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'type': json['type'],
        'country': json['country'],
        'bvn': json['bvn'],
        'bankCode': json['bank_code'],
        'accountNumber': json['account_number'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function CustomerValidationToJSON(value?: CustomerValidation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first_name': value.firstName,
        'last_name': value.lastName,
        'type': value.type,
        'country': value.country,
        'bvn': value.bvn,
        'bank_code': value.bankCode,
        'account_number': value.accountNumber,
        'value': value.value,
    };
}


