/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DedicatedVirtualAccountCreate
 */
export interface DedicatedVirtualAccountCreate {
    /**
     * Customer ID or code
     * @type {string}
     * @memberof DedicatedVirtualAccountCreate
     */
    customer: string;
    /**
     * The bank slug for preferred bank. To get a list of available banks, use the List Providers endpoint
     * @type {string}
     * @memberof DedicatedVirtualAccountCreate
     */
    preferredBank?: string;
    /**
     * Subaccount code of the account you want to split the transaction with
     * @type {string}
     * @memberof DedicatedVirtualAccountCreate
     */
    subaccount?: string;
    /**
     * Split code consisting of the lists of accounts you want to split the transaction with
     * @type {string}
     * @memberof DedicatedVirtualAccountCreate
     */
    splitCode?: string;
}

export function DedicatedVirtualAccountCreateFromJSON(json: any): DedicatedVirtualAccountCreate {
    return DedicatedVirtualAccountCreateFromJSONTyped(json, false);
}

export function DedicatedVirtualAccountCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DedicatedVirtualAccountCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customer': json['customer'],
        'preferredBank': !exists(json, 'preferred_bank') ? undefined : json['preferred_bank'],
        'subaccount': !exists(json, 'subaccount') ? undefined : json['subaccount'],
        'splitCode': !exists(json, 'split_code') ? undefined : json['split_code'],
    };
}

export function DedicatedVirtualAccountCreateToJSON(value?: DedicatedVirtualAccountCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer': value.customer,
        'preferred_bank': value.preferredBank,
        'subaccount': value.subaccount,
        'split_code': value.splitCode,
    };
}


