/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EFT
 */
export interface EFT {
    /**
     * The EFT provider
     * @type {string}
     * @memberof EFT
     */
    provider?: string;
}

export function EFTFromJSON(json: any): EFT {
    return EFTFromJSONTyped(json, false);
}

export function EFTFromJSONTyped(json: any, ignoreDiscriminator: boolean): EFT {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
    };
}

export function EFTToJSON(value?: EFT | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provider': value.provider,
    };
}


