export interface PageFetchData {
  /**  */
  integration: number;
  /**  */
  domain: string;
  /**  */
  name: string;
  /**  */
  description: unknown;
  /**  */
  amount: number;
  /**  */
  currency: string;
  /**  */
  slug: string;
  /**  */
  custom_fields: unknown;
  /**  */
  type: string;
  /**  */
  redirect_url: unknown;
  /**  */
  success_message: unknown;
  /**  */
  collect_phone: boolean;
  /**  */
  active: boolean;
  /**  */
  published: boolean;
  /**  */
  migrate: boolean;
  /**  */
  notification_email: unknown;
  /**  */
  metadata: unknown;
  /**  */
  split_code: unknown;
  /**  */
  id: number;
  /**  */
  createdAt: string;
  /**  */
  updatedAt: string;
}
