export interface PageAddProductsData {
  /**  */
  integration: number;
  /**  */
  plan: unknown;
  /**  */
  domain: string;
  /**  */
  name: string;
  /**  */
  description: unknown;
  /**  */
  amount: unknown;
  /**  */
  currency: string;
  /**  */
  slug: string;
  /**  */
  custom_fields: unknown;
  /**  */
  type: string;
  /**  */
  redirect_url: unknown;
  /**  */
  success_message: unknown;
  /**  */
  collect_phone: boolean;
  /**  */
  active: boolean;
  /**  */
  published: boolean;
  /**  */
  migrate: boolean;
  /**  */
  notification_email: unknown;
  /**  */
  metadata: unknown;
  /**  */
  split_code: unknown;
  /**  */
  id: number;
  /**  */
  createdAt: string;
  /**  */
  updatedAt: string;
  /**  */
  products: Array<{ product_id: number; name: string; description: string; product_code: string; page: number; price: number; currency: string; quantity: number; type: string; features: unknown; is_shippable: number; domain: string; integration: number; active: number; in_stock: number }>;
}
