export interface PlanFetchData {
  /**  */
  subscriptions: Array<unknown>;
  /**  */
  pages: Array<unknown>;
  /**  */
  domain: string;
  /**  */
  name: string;
  /**  */
  plan_code: string;
  /**  */
  description: unknown;
  /**  */
  amount: number;
  /**  */
  interval: string;
  /**  */
  invoice_limit: number;
  /**  */
  send_invoices: boolean;
  /**  */
  send_sms: boolean;
  /**  */
  hosted_page: boolean;
  /**  */
  hosted_page_url: unknown;
  /**  */
  hosted_page_summary: unknown;
  /**  */
  currency: string;
  /**  */
  migrate: boolean;
  /**  */
  is_deleted: boolean;
  /**  */
  is_archived: boolean;
  /**  */
  id: number;
  /**  */
  integration: number;
  /**  */
  createdAt: string;
  /**  */
  updatedAt: string;
  /**  */
  pages_count: number;
  /**  */
  subscribers_count: number;
  /**  */
  subscriptions_count: number;
  /**  */
  active_subscriptions_count: number;
  /**  */
  total_revenue: number;
  /**  */
  subscribers: Array<unknown>;
}
