export interface ProductCreateData {
  /**  */
  variants_options: Array<unknown>;
  /**  */
  variants: Array<unknown>;
  /**  */
  name: string;
  /**  */
  description: string;
  /**  */
  currency: string;
  /**  */
  price: number;
  /**  */
  quantity: number;
  /**  */
  type: string;
  /**  */
  is_shippable: boolean;
  /**  */
  unlimited: boolean;
  /**  */
  files: Array<unknown>;
  /**  */
  shipping_fields: { delivery_note: string; shipping_address: string; shipping_fees: Array<unknown> };
  /**  */
  integration: number;
  /**  */
  domain: string;
  /**  */
  metadata: { background_color: string };
  /**  */
  slug: string;
  /**  */
  product_code: string;
  /**  */
  quantity_sold: number;
  /**  */
  active: boolean;
  /**  */
  deleted_at: unknown;
  /**  */
  in_stock: boolean;
  /**  */
  minimum_orderable: number;
  /**  */
  maximum_orderable: number;
  /**  */
  redirect_url?: string;
  /**  */
  low_stock_alert: boolean;
  /**  */
  id: number;
  /**  */
  createdAt: string;
  /**  */
  updatedAt: string;
}
