export interface ProductFetchData {
  /**  */
  digital_assets: Array<unknown>;
  /**  */
  integration: number;
  /**  */
  name: string;
  /**  */
  description: string;
  /**  */
  product_code: string;
  /**  */
  price: number;
  /**  */
  currency: string;
  /**  */
  quantity: number;
  /**  */
  quantity_sold: unknown;
  /**  */
  type: string;
  /**  */
  files: Array<unknown>;
  /**  */
  file_path: unknown;
  /**  */
  is_shippable: boolean;
  /**  */
  shipping_fields: { delivery_note: string; shipping_address: string; shipping_fees: Array<unknown> };
  /**  */
  unlimited: boolean;
  /**  */
  domain: string;
  /**  */
  active: boolean;
  /**  */
  features: unknown;
  /**  */
  in_stock: boolean;
  /**  */
  metadata: { background_color: string };
  /**  */
  slug: string;
  /**  */
  success_message: unknown;
  /**  */
  redirect_url: unknown;
  /**  */
  split_code: unknown;
  /**  */
  notification_emails: unknown;
  /**  */
  minimum_orderable: number;
  /**  */
  maximum_orderable: unknown;
  /**  */
  low_stock_alert: boolean;
  /**  */
  stock_threshold: unknown;
  /**  */
  expires_in: unknown;
  /**  */
  id: number;
  /**  */
  createdAt: string;
  /**  */
  updatedAt: string;
}
