export interface RefundFetchData {
  /**  */
  integration: number;
  /**  */
  transaction: number;
  /**  */
  dispute: unknown;
  /**  */
  settlement: unknown;
  /**  */
  id: number;
  /**  */
  domain: string;
  /**  */
  currency: string;
  /**  */
  amount: number;
  /**  */
  status: string;
  /**  */
  refunded_at: unknown;
  /**  */
  refunded_by: string;
  /**  */
  customer_note: string;
  /**  */
  merchant_note: string;
  /**  */
  deducted_amount: number;
  /**  */
  fully_deducted: number;
  /**  */
  createdAt: string;
  /**  */
  bank_reference: unknown;
  /**  */
  transaction_reference: string;
  /**  */
  reason: string;
  /**  */
  customer: { id: number; first_name: string; last_name: string; email: string; customer_code: string; phone: string; metadata: string; risk_action: string; international_format_phone: string };
  /**  */
  refund_type: string;
  /**  */
  transaction_amount: number;
  /**  */
  initiated_by: string;
  /**  */
  refund_channel: string;
  /**  */
  session_id: unknown;
  /**  */
  collect_account_number: boolean;
}
