/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubaccountUpdate
 */
export interface SubaccountUpdate {
    /**
     * Name of business for subaccount
     * @type {string}
     * @memberof SubaccountUpdate
     */
    businessName?: string;
    /**
     * Bank code for the bank. You can get the list of Bank Codes by calling the List Banks endpoint.
     * @type {string}
     * @memberof SubaccountUpdate
     */
    settlementBank?: string;
    /**
     * Bank account number
     * @type {string}
     * @memberof SubaccountUpdate
     */
    accountNumber?: string;
    /**
     * Activate or deactivate a subaccount
     * @type {boolean}
     * @memberof SubaccountUpdate
     */
    active?: boolean;
    /**
     * Customer's phone number
     * @type {number}
     * @memberof SubaccountUpdate
     */
    percentageCharge?: number;
    /**
     * A description for this subaccount
     * @type {string}
     * @memberof SubaccountUpdate
     */
    description?: string;
    /**
     * A contact email for the subaccount
     * @type {string}
     * @memberof SubaccountUpdate
     */
    primaryContactEmail?: string;
    /**
     * The name of the contact person for this subaccount
     * @type {string}
     * @memberof SubaccountUpdate
     */
    primaryContactName?: string;
    /**
     * A phone number to call for this subaccount
     * @type {string}
     * @memberof SubaccountUpdate
     */
    primaryContactPhone?: string;
    /**
     * Stringified JSON object of custom data
     * @type {string}
     * @memberof SubaccountUpdate
     */
    metadata?: string;
}

export function SubaccountUpdateFromJSON(json: any): SubaccountUpdate {
    return SubaccountUpdateFromJSONTyped(json, false);
}

export function SubaccountUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubaccountUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'businessName': !exists(json, 'business_name') ? undefined : json['business_name'],
        'settlementBank': !exists(json, 'settlement_bank') ? undefined : json['settlement_bank'],
        'accountNumber': !exists(json, 'account_number') ? undefined : json['account_number'],
        'active': !exists(json, 'active') ? undefined : json['active'],
        'percentageCharge': !exists(json, 'percentage_charge') ? undefined : json['percentage_charge'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'primaryContactEmail': !exists(json, 'primary_contact_email') ? undefined : json['primary_contact_email'],
        'primaryContactName': !exists(json, 'primary_contact_name') ? undefined : json['primary_contact_name'],
        'primaryContactPhone': !exists(json, 'primary_contact_phone') ? undefined : json['primary_contact_phone'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function SubaccountUpdateToJSON(value?: SubaccountUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'business_name': value.businessName,
        'settlement_bank': value.settlementBank,
        'account_number': value.accountNumber,
        'active': value.active,
        'percentage_charge': value.percentageCharge,
        'description': value.description,
        'primary_contact_email': value.primaryContactEmail,
        'primary_contact_name': value.primaryContactName,
        'primary_contact_phone': value.primaryContactPhone,
        'metadata': value.metadata,
    };
}


