export interface SubaccountUpdateData {
  /**  */
  domain: string;
  /**  */
  subaccount_code: string;
  /**  */
  account_name?: string;
  /**  */
  business_name: string;
  /**  */
  description: string;
  /**  */
  primary_contact_name: string;
  /**  */
  primary_contact_email: string;
  /**  */
  primary_contact_phone: string;
  /**  */
  metadata: string;
  /**  */
  percentage_charge: number;
  /**  */
  is_verified: boolean;
  /**  */
  settlement_bank: string;
  /**  */
  account_number: string;
  /**  */
  settlement_schedule: string;
  /**  */
  active: boolean;
  /**  */
  migrate: boolean;
  /**  */
  currency: string;
  /**  */
  product: string;
  /**  */
  id: number;
  /**  */
  integration: number;
  /**  */
  bank: number;
  /**  */
  managed_by_integration: number;
  /**  */
  createdAt: string;
  /**  */
  updatedAt: string;
}
