/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionToggle
 */
export interface SubscriptionToggle {
    /**
     * Subscription code
     * @type {string}
     * @memberof SubscriptionToggle
     */
    code: string;
    /**
     * Email token
     * @type {string}
     * @memberof SubscriptionToggle
     */
    token: string;
}

export function SubscriptionToggleFromJSON(json: any): SubscriptionToggle {
    return SubscriptionToggleFromJSONTyped(json, false);
}

export function SubscriptionToggleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionToggle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'token': json['token'],
    };
}

export function SubscriptionToggleToJSON(value?: SubscriptionToggle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'token': value.token,
    };
}


