/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferInitiate
 */
export interface TransferInitiate {
    /**
     * Where should we transfer from? Only balance is allowed for now
     * @type {string}
     * @memberof TransferInitiate
     */
    source: string;
    /**
     * Amount to transfer in kobo if currency is NGN and pesewas if currency is GHS.
     * @type {string}
     * @memberof TransferInitiate
     */
    amount: string;
    /**
     * The transfer recipient's code
     * @type {string}
     * @memberof TransferInitiate
     */
    recipient: string;
    /**
     * The reason or narration for the transfer.
     * @type {string}
     * @memberof TransferInitiate
     */
    reason?: string;
    /**
     * Specify the currency of the transfer. Defaults to NGN.
     * @type {string}
     * @memberof TransferInitiate
     */
    currency?: string;
    /**
     * If specified, the field should be a unique identifier (in lowercase) for the object. 
     * Only -,_ and alphanumeric characters are allowed.
     * @type {string}
     * @memberof TransferInitiate
     */
    reference?: string;
}

export function TransferInitiateFromJSON(json: any): TransferInitiate {
    return TransferInitiateFromJSONTyped(json, false);
}

export function TransferInitiateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferInitiate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'source': json['source'],
        'amount': json['amount'],
        'recipient': json['recipient'],
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'reference': !exists(json, 'reference') ? undefined : json['reference'],
    };
}

export function TransferInitiateToJSON(value?: TransferInitiate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'source': value.source,
        'amount': value.amount,
        'recipient': value.recipient,
        'reason': value.reason,
        'currency': value.currency,
        'reference': value.reference,
    };
}


