/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferResendOTP
 */
export interface TransferResendOTP {
    /**
     * The transfer code that requires an OTP validation
     * @type {string}
     * @memberof TransferResendOTP
     */
    transferCode: string;
    /**
     * Either resend_otp or transfer
     * @type {string}
     * @memberof TransferResendOTP
     */
    reason: string;
}

export function TransferResendOTPFromJSON(json: any): TransferResendOTP {
    return TransferResendOTPFromJSONTyped(json, false);
}

export function TransferResendOTPFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferResendOTP {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transferCode': json['transfer_code'],
        'reason': json['reason'],
    };
}

export function TransferResendOTPToJSON(value?: TransferResendOTP | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transfer_code': value.transferCode,
        'reason': value.reason,
    };
}


