export interface TransferInitiateData {
  /**  */
  transfersessionid: Array<unknown>;
  /**  */
  transfertrials: Array<unknown>;
  /**  */
  domain: string;
  /**  */
  amount: number;
  /**  */
  currency: string;
  /**  */
  reference: string;
  /**  */
  source: string;
  /**  */
  source_details: unknown;
  /**  */
  reason: string;
  /**  */
  status: string;
  /**  */
  failures: unknown;
  /**  */
  transfer_code: string;
  /**  */
  titan_code: unknown;
  /**  */
  transferred_at: unknown;
  /**  */
  id: number;
  /**  */
  integration: number;
  /**  */
  request: number;
  /**  */
  recipient: number;
  /**  */
  createdAt: string;
  /**  */
  updatedAt: string;
}
