/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferRecipientUpdate
 */
export interface TransferRecipientUpdate {
    /**
     * Recipient's name
     * @type {string}
     * @memberof TransferRecipientUpdate
     */
    name?: string;
    /**
     * Recipient's email address
     * @type {string}
     * @memberof TransferRecipientUpdate
     */
    email?: string;
}

export function TransferRecipientUpdateFromJSON(json: any): TransferRecipientUpdate {
    return TransferRecipientUpdateFromJSONTyped(json, false);
}

export function TransferRecipientUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferRecipientUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function TransferRecipientUpdateToJSON(value?: TransferRecipientUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
    };
}


