/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the Paystack Node library: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TransferRecipientCreate,
    TransferRecipientCreateFromJSON,
    TransferRecipientCreateFromJSONTyped,
    TransferRecipientCreateToJSON,
} from './';

/**
 * 
 * @export
 * @interface TransferRecipientBulk
 */
export interface TransferRecipientBulk {
    /**
     * A list of transfer recipient object. Each object should contain type, name, and bank_code. 
     * Any Create Transfer Recipient param can also be passed.
     * @type {Array<TransferRecipientCreate>}
     * @memberof TransferRecipientBulk
     */
    batch: Array<TransferRecipientCreate>;
}

export function TransferRecipientBulkFromJSON(json: any): TransferRecipientBulk {
    return TransferRecipientBulkFromJSONTyped(json, false);
}

export function TransferRecipientBulkFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferRecipientBulk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'batch': ((json['batch'] as Array<any>).map(TransferRecipientCreateFromJSON)),
    };
}

export function TransferRecipientBulkToJSON(value?: TransferRecipientBulk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'batch': ((value.batch as Array<any>).map(TransferRecipientCreateToJSON)),
    };
}


