import { ApiClient } from "./core/api-client.js";
import type { ApiClientConfig } from "./core/types.js";
import { TransactionApi } from "./apis/transaction.js";
import { ChargeApi } from "./apis/charge.js";
import { BulkChargeApi } from "./apis/bulk-charge.js";
import { SubaccountApi } from "./apis/subaccount.js";
import { SplitApi } from "./apis/split.js";
import { TerminalApi } from "./apis/terminal.js";
import { VirtualTerminalApi } from "./apis/virtual-terminal.js";
import { CustomerApi } from "./apis/customer.js";
import { DirectDebitApi } from "./apis/direct-debit.js";
import { DedicatedVirtualAccountApi } from "./apis/dedicated-virtual-account.js";
import { ApplePayApi } from "./apis/apple-pay.js";
import { PlanApi } from "./apis/plan.js";
import { SubscriptionApi } from "./apis/subscription.js";
import { TransferRecipientApi } from "./apis/transfer-recipient.js";
import { TransferApi } from "./apis/transfer.js";
import { BalanceApi } from "./apis/balance.js";
import { PaymentRequestApi } from "./apis/payment-request.js";
import { ProductApi } from "./apis/product.js";
import { StorefrontApi } from "./apis/storefront.js";
import { OrderApi } from "./apis/order.js";
import { PageApi } from "./apis/page.js";
import { SettlementApi } from "./apis/settlement.js";
import { IntegrationApi } from "./apis/integration.js";
import { RefundApi } from "./apis/refund.js";
import { DisputeApi } from "./apis/dispute.js";
import { BankApi } from "./apis/bank.js";
import { MiscellaneousApi } from "./apis/miscellaneous.js";

export class Paystack {
  public readonly transaction: TransactionApi;
  public readonly charge: ChargeApi;
  public readonly bulkCharge: BulkChargeApi;
  public readonly subaccount: SubaccountApi;
  public readonly split: SplitApi;
  public readonly terminal: TerminalApi;
  public readonly virtualTerminal: VirtualTerminalApi;
  public readonly customer: CustomerApi;
  public readonly directDebit: DirectDebitApi;
  public readonly dedicatedVirtualAccount: DedicatedVirtualAccountApi;
  public readonly applePay: ApplePayApi;
  public readonly plan: PlanApi;
  public readonly subscription: SubscriptionApi;
  public readonly transferRecipient: TransferRecipientApi;
  public readonly transfer: TransferApi;
  public readonly balance: BalanceApi;
  public readonly paymentRequest: PaymentRequestApi;
  public readonly product: ProductApi;
  public readonly storefront: StorefrontApi;
  public readonly order: OrderApi;
  public readonly page: PageApi;
  public readonly settlement: SettlementApi;
  public readonly integration: IntegrationApi;
  public readonly refund: RefundApi;
  public readonly dispute: DisputeApi;
  public readonly bank: BankApi;
  public readonly miscellaneous: MiscellaneousApi;

  constructor(config: ApiClientConfig) {
    const client = new ApiClient(config);
    this.transaction = new TransactionApi(client);
    this.charge = new ChargeApi(client);
    this.bulkCharge = new BulkChargeApi(client);
    this.subaccount = new SubaccountApi(client);
    this.split = new SplitApi(client);
    this.terminal = new TerminalApi(client);
    this.virtualTerminal = new VirtualTerminalApi(client);
    this.customer = new CustomerApi(client);
    this.directDebit = new DirectDebitApi(client);
    this.dedicatedVirtualAccount = new DedicatedVirtualAccountApi(client);
    this.applePay = new ApplePayApi(client);
    this.plan = new PlanApi(client);
    this.subscription = new SubscriptionApi(client);
    this.transferRecipient = new TransferRecipientApi(client);
    this.transfer = new TransferApi(client);
    this.balance = new BalanceApi(client);
    this.paymentRequest = new PaymentRequestApi(client);
    this.product = new ProductApi(client);
    this.storefront = new StorefrontApi(client);
    this.order = new OrderApi(client);
    this.page = new PageApi(client);
    this.settlement = new SettlementApi(client);
    this.integration = new IntegrationApi(client);
    this.refund = new RefundApi(client);
    this.dispute = new DisputeApi(client);
    this.bank = new BankApi(client);
    this.miscellaneous = new MiscellaneousApi(client);
  }
}

export type { ApiClientConfig, ApiResponse } from "./core/types.js";
export * from "./models/index.js";
